# Generated by Django 5.1.7 on 2025-04-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_add_sample_jobs'),
        ('jobapp', '0016_alter_job_user'),
    ]

    operations = [
    ]
