# Generated by Django 5.1.7 on 2025-04-12 04:30

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_merge_0016_add_sample_jobs_0016_alter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cover_letter',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Write your cover letter here', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='experience',
            field=models.TextField(blank=True, help_text='Describe your relevant experience', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.TextField(blank=True, help_text='List your relevant skills', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='jobapp.category'),
        ),
    ]
