# Generated by Django 5.1.7 on 2025-04-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
