# Generated by Django 5.1.7 on 2025-05-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_jobrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaskContactMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_submitted', models.DateTimeField()),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlaskJobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date_applied', models.DateTimeField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'job_application',
                'managed': False,
            },
        ),
    ]
