# Generated by Django 5.1.7 on 2025-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0023_flaskcontactmessage_flaskjobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaskJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('work_mode', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('date_posted', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
    ]
